
import Foundation

// =====================================================
// MODEL: ChatMessage
// =====================================================
// PURPOSE:
// Represents a single message inside the RecalllQ
// AI Study Chat.
//
// Each chat conversation is made up of multiple
// ChatMessage objects.
//
// FLOW:
//
// Student
//    ↓
// ChatMessage
//    ↓
// Chat Conversation
//    ↓
// AIService
//    ↓
// RecalllQ AI Response
//
// This model is Codable so conversations can be
// saved locally and restored later.
// =====================================================

struct ChatMessage: Identifiable, Codable, Equatable {

    // =====================================================
    // IDENTITY
    // =====================================================

    /// Unique identifier for this message.
    var id: UUID = UUID()

    // =====================================================
    // MESSAGE CONTENT
    // =====================================================

    /// The actual text displayed in the chat.
    var content: String

    // =====================================================
    // MESSAGE SENDER
    // =====================================================

    /// Identifies whether the message was written by
    /// the student or generated by RecalllQ AI.
    var role: ChatMessageRole

    // =====================================================
    // TIMESTAMP
    // =====================================================

    /// Date and time when the message was created.
    var timestamp: Date = Date()

    // =====================================================
    // INITIALIZER
    // =====================================================

    init(
        id: UUID = UUID(),
        content: String,
        role: ChatMessageRole,
        timestamp: Date = Date()
    ) {
        self.id = id
        self.content = content
        self.role = role
        self.timestamp = timestamp
    }
}

// =====================================================
// ENUM: ChatMessageRole
// =====================================================
// PURPOSE:
// Identifies who created a chat message.
//
// student = Message written by the student
// assistant = Response generated by RecalllQ AI
//
// Codable allows this information to be stored together
// with chat history.
// =====================================================

enum ChatMessageRole: String, Codable, Equatable {

    // =====================================================
    // STUDENT MESSAGE
    // =====================================================

    case student

    // =====================================================
    // AI ASSISTANT MESSAGE
    // =====================================================

    case assistant
}

